### ISSUE TITLE
Fixed auth token (Client-ID)

### ISSUE THREAD

**Issue by cyxin577** [Adonai/holywarsoo-android#1]
Hi, 
I find that the authorization header added when the app uploads image in Network.kt is a fixed string.
![图片](https://user-images.githubusercontent.com/69659437/124896010-a60e0500-e00f-11eb-9422-ab55ccf1340e.png)
May it be hijacked? I think the auth token is supposed to be generated by the server side using some encryption algorithms.
Do you confirm this bug? Thanks.

**Comment by Kaned1as** [comment]
Yes you're right, will fix this
